### ISSUE TITLE
ERROR when install.sh runs

### ISSUE THREAD

**Issue by zax123** [GiuseppeGalilei/Unifi-Network-Application#2]
Is anyone else getting this error when running install.sh? I get this error and the dockers are not created (obviously since the docker-compose.yml file isn't interpreted correctly):

ERROR: In file './docker-compose.yml', service 'name' must be a mapping not a string.

**Comment by GiuseppeGalilei** [comment]
Thanks for your feedback! I just released this script so I guess unfortunately a little bit of testing is still required.
It is working fine on my end, can you give more information about your issue?

Are you running the script through the "oneliner" command? What type of system are you running it on?
Version of docker and docker-compose will be useful too.

**Comment by zax123** [comment]
Hi there, I am installing on an Ubuntu 22.04 host which has docker version 23.0.2 and docker-compose version 1.25.0.

Yup, I used the one-liner which executes install.sh and during the install with default options (ENTER, ENTER), it popped that error and never gets around to creating the containers.

I suspect it's a problem with the docker and docker-compose versions. I think later versions of docker compose are more forgiving with respect to the format of the yaml, but I'm not sure.

**Comment by GiuseppeGalilei** [comment]
Thanks!
I think you are right, from some quick searches it seems this kind of issue gets solved by upgrading docker-compose.
I'll try to find a way to make the script compatible with older versions too, if possible.

In the meantime, if you are in a hurry, you can deploy it manually using the "Generic" installation for the Old compose version.
https://github.com/GiuseppeGalilei/Unifi-Network-Application/tree/main/Unifi%20network%20Application%20-%20Generic/older%20docker%20compose%20version%20(before%202.23.1)

**Comment by zax123** [comment]
Oh thanks, let me try that now!

**Comment by zax123** [comment]
Same problem unfortunately :(

`root@beauty:/home/robert/unifi# docker-compose up
ERROR: In file './docker-compose.yml', service 'name' must be a mapping not a string.`

**Comment by GiuseppeGalilei** [comment]
Sorry about that.
Maybe you can try modifying the compose file to fix it for your use case.
If you succeed please share the solution so that I can implement it.

**Comment by zax123** [comment]
Oops, this system is Ubuntu 20.04. I'm going to upgrade it to 22.04 tomorrow. Maybe that will fix it. :)

**Comment by GiuseppeGalilei** [comment]
Hope it'll work!
Keep me posted.

Once you upgrade, try this version:
wget -O install.sh https://raw.githubusercontent.com/GiuseppeGalilei/Unifi-Network-Application/oneliner_dev/OneLiner/install.sh && chmod +x install.sh && ./install.sh

**Comment by zax123** [comment]
Hi Giuseppe, I've upgraded to Ubuntu 22.04 now and I'm getting this message when running the dev script:

`services.unifi-network-application.depends_on.unifi-db Additional property required is not allowed`

I suspect it's a docker-compose.yml thing again? This is running version 23.02 of docker...

**Comment by GiuseppeGalilei** [comment]
> I suspect it's a docker-compose.yml thing again? This is running version 23.02 of docker...

Strange...
Try running "docker compose version" and tell me the version

Just to double check, you are using this command, right? 
wget -O install.sh https://raw.githubusercontent.com/GiuseppeGalilei/Unifi-Network-Application/oneliner_dev/OneLiner/install.sh && chmod +x install.sh && ./install.sh

**Comment by zax123** [comment]
I figured it out. The version of docker (23.02) was from an old (18.04) version of Ubuntu. I had to manually remove that and upgrade to the newest version (25.04). 

After doing that, your script worked beautifully.

I'm about to login, thanks!

**Comment by GiuseppeGalilei** [comment]
Cool! Thanks for your help and feedback!
