### ISSUE TITLE
Error on install.sh - Wainting containers to start

### ISSUE THREAD

**Issue by OberfragGER** [GiuseppeGalilei/Unifi-Network-Application#3]
I use Debian12 and installed docker-compose.

`Enter an absolute path to place the installation directory (or press Enter for the home folder): /mnt/Docker/Unifi
Installation directory already exists. Grant sudo access and let the script handle it, or delete it manually and restart the script.

Enter the password for the database (or press Enter for the default value: pass):

ERROR: The Compose file './docker-compose.yml' is invalid because:
'name' does not match any of the regexes: '^x-'

You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
services.unifi-network-application.depends_on contains unsupported option: 'required'
Waiting for containers to start...
Waiting for containers to start...
Waiting for containers to start...
Waiting for containers to start...
`

It creates some folders at the paths. Thats it.
After: "Waiting for containers to start..." nothing happens

**Comment by GiuseppeGalilei** [comment]
Can you tell me the docker and docker-compose version you are using?

The "waiting for containers" goes on indefinetely because the error in dealing with the compose file messed up the process.
As said in the other issue, I'm still experimenting, any help finding bugs is welcomed.

**Comment by OberfragGER** [comment]
I tried again. Steps to reproduce
Docker version 25.0.4, build 1a576c5
Docker Compose version v2.24.7

wget your script...
`Error: docker-compose is not installed.`
Then: apt-get install docker-compose

root@docker:~# docker-compose version
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.11.2
OpenSSL version: OpenSSL 3.0.11 19 Sep 2023

I think your script reffers to docker-compose instead of docker compose. So docker-compose is older...

**Comment by GiuseppeGalilei** [comment]
Ok, I tried to remove the "docker-compose" dependency and use "docker compose" instead.
From a quick search it seems as if "docker-compose" is the old, deprecated, version of "docker compose".
For testing I'm using WSL2, where it seems "docker-compose" is just an alias for "docker compose", which might be the reason why I didn't encounter this issue.

You can try installing with the updated script from the oneliner_dev branch.
wget -O install.sh https://raw.githubusercontent.com/GiuseppeGalilei/Unifi-Network-Application/oneliner_dev/OneLiner/install.sh && chmod +x install.sh && ./install.sh

**Comment by OberfragGER** [comment]
> Ok, I tried to remove the "docker-compose" dependency and use "docker compose" instead. From a quick search it seems as if "docker-compose" is the old, deprecated, version of "docker compose". For testing I'm using WSL2, where it seems "docker-compose" is just an alias for "docker compose", which might be the reason why I didn't encounter this issue.
> 
> You can try installing with the updated script from the oneliner_dev branch. wget -O install.sh https://raw.githubusercontent.com/GiuseppeGalilei/Unifi-Network-Application/oneliner_dev/OneLiner/install.sh && chmod +x install.sh && ./install.sh

looks like its working. just startet the script. everything rund fine and i could login to my Unfi-Account.

**Comment by GiuseppeGalilei** [comment]
> looks like its working. just startet the script. everything rund fine and i could login to my Unfi-Account.

Cool! Thanks for your help and feedback!
