### ISSUE TITLE
Docker Compose V2 not included by default in most Base OS Images

### ISSUE THREAD

**Issue by xChesher** [GiuseppeGalilei/Unifi-Network-Application#4]
You may wanna include this guide as a prerequisite, as the normal docker and compose installations cant be called from your script.

https://gcore.com/learning/how-to-install-docker-compose-on-ubuntu/

**Comment by GiuseppeGalilei** [comment]
What issues are you encountering? Can you post the errors you get?

**Comment by xChesher** [comment]
> What issues are you encountering? Can you post the errors you get?

So essentially if you were to spin up a new Ubuntu VM. After updating and upgrading the packages on the device, and installing docker from apt-get you will not be able to run "docker compose up" which is called by your script. You would need to essentially follow the guide above to install the docker-compose-plugin to the current docker plugins folder. After this is done the install.sh runs perfectly. 

There might be an easier way that I am not aware of, or this could be exclusive to Ubuntu. But this has been my experience running this script.

**Comment by GiuseppeGalilei** [comment]
Ok, now I get it. Thanks for the heads up! I took the availability of compose for granted, I'll implement a check for it.
Anyway, how did the script handle it? Did it throw out some meaningful error?

**Comment by xChesher** [comment]
It didn't really give any great verbose responses. I was trying to force the script to run in verbose mode but the verbose logs seem to mess with the input and just freaks out immediately. It pretty much just tried to run docker compose up -d and then spat out that it does not recognize docker compose as a valid command

Edit: I essentially had to read through the script to understand why it was not working ( Luckily it was relatively obvious haha )

PS.. Thank you for this script this was by far the easiest way even with the troubleshooting included

**Comment by GiuseppeGalilei** [comment]
Thanks! Glad to have been helpful!
If you want, consider leaving a star to support the project.

**Comment by xChesher** [comment]
Will do!
