### ISSUE TITLE
Error when Docker compose up -d

### ISSUE THREAD

**Issue by BuildNat** [GiuseppeGalilei/Unifi-Network-Application#5]
Hello Giuseppe, 

i've an issue with the command docker compose up-d 

unknown shorthand flag: 'd' in -d
See 'docker --help'.

thank you for your work 👍

**Comment by BuildNat** [comment]
> _No description provided._

**Comment by BuildNat** [comment]
Docker compose is just not installed.

**Comment by GiuseppeGalilei** [comment]
Thanks for the feedback! I just implemented a fix for it, give it a try if you can
