### ISSUE TITLE
Unable to Create Directories

### ISSUE THREAD

**Issue by DarkSideSumthin** [GiuseppeGalilei/Unifi-Network-Application#6]
Good Evening Giuseppe!
Thank you so much for this script it looks amazing!

My Issue: Unable to create directories at the path "/docker".

Error output from the script below.
> Enter an absolute path to place the installation directory (or press Enter for the home folder): /docker
> mkdir: cannot create directory ‘/docker/unifi’: Permission denied

Recreate issue: Run the single line with or without the sudo command and use the absolute path "/docker".

/docker and its recursive directories are owned by root as they were created by the docker RUN command.

Is there any way to run this command as a sudoer or work around this?

**Comment by GiuseppeGalilei** [comment]
Thanks for your feedback! And good morning from this side of the world 😅
By default I didn't want the script to ask for more permissions than absolutely needed, in the future I might implement more checks for it. 
In the meantime, you can run the whole script as root by executing "sudo su" just before calling the script.
Let me know if it works out!

**Comment by DarkSideSumthin** [comment]
I tried that the moment you replied and after leaving it running for a few hours it's running great! 
Thank you so much!

**Comment by GiuseppeGalilei** [comment]
Happy to help! Consider leaving a star if you found it useful
