### ISSUE TITLE
Unifi Network Application error

### ISSUE THREAD

**Issue by zeushomeserver** [GiuseppeGalilei/Unifi-Network-Application#8]
I am getting this error in logs on Unifi Network Application's container: 

`s6-rc-compile: fatal: invalid /etc/s6-overlay/s6-rc.d/ci-service-check/type: must be oneshot, longrun, or bundle`

MongoDB container is working as intended.

**Comment by GiuseppeGalilei** [comment]
No idea about what that may be😕... can you give more context? Have you already tried googling the issue?

**Comment by zeushomeserver** [comment]
Regarding context, I am trying to set it up inside a Debian VM on Proxmox. I tried googling this issue but nothing relevant came up.

**Comment by GiuseppeGalilei** [comment]
did you try the manual installation process(for which you can find instruction in the repo)? give it a go, it is very easy
Then we can isolate if it is the script fault or the issue lies in your setup

**Comment by zeushomeserver** [comment]
It seems that deleting the image and redownloading it solved my problem. Thanks!

**Comment by GiuseppeGalilei** [comment]
I'm happy you found your solution! Don't forget to leave a star, we are getting to 50 😂
